### ISSUE TITLE
Got a ModuleNotFoundError for 'pyontutils' when using NeuronLangExample.ipynb

### ISSUE THREAD

**Issue by MFSY** [tgbugs/pyontutils#21]
Hi,
I've followed the [prerequisites](https://github.com/tgbugs/pyontutils/blob/master/docs/neurons_notebook.md) steps in order to set up an env for [NeuronLangExample.ipynb](https://github.com/tgbugs/pyontutils/blob/master/docs/NeuronLangExample.ipynb). The set up went well except for the following two operations:

```
  pip install dist/pyontutils-*-py3-none-any.whl
```
and

```
pip install dist/rdflib-*-py3-none-any.whl
```
that both finished with the following (non blocking) error:
```
Failed building wheel for mysql-connector
```
 
The notebook is launched at end but it is not working with the following error:
ModuleNotFoundError: No module named 'pyontutils'

I am using python 3.6.

Any chance you know what's wrong with this.

**Comment by tgbugs** [comment]
Yes, it is the dreaded mysql-connector bug.

The full solution is documented in step 3 here https://github.com/tgbugs/pyontutils/#installation, but the quick solution is just to run `pip install mysql-connector==2.1.6` and then `pip install dist/pyontutils-*-py3-none-any.whl` after which it should work.

I will update the neurons_notebook documentation to reflect the updated preferred installation method which is in the main [README](https://github.com/tgbugs/pyontutils/blob/master/README.md). If you are up for it using the new Pipenv setup documented there will probably make life easier, but I have not tested the full setup with that yet.

**Comment by tgbugs** [comment]
Currently updating the documentation since it was VERY out of date. The new instructions should be much simpler and I have removed mysql-connector and psycopg2 from the dependencies so that installation won't be as complicated.
