### ISSUE TITLE
break allen cell types into two files and follow the pattern from huang2017

### ISSUE THREAD

**Issue by tgbugs** [tgbugs/pyontutils#30]
Due to the... large number of implicit conventions in neuron lang, many features fail to work because all en cell types does not follow the pattern those conventions require. Needs to be reworked to follow those convetions. @tmsincomb

**Comment by tgbugs** [comment]
1. In this case just the actual layout and scoping of the various parts of the code. Basically the top level control structure for neuron lang need to be in the top level of a file, not burried in a class. See for example.
https://github.com/tgbugs/pyontutils/blob/master/pyontutils/neuron_models/huang2017.py#L14
https://github.com/tgbugs/pyontutils/blob/master/pyontutils/neuron_models/huang2017.py#L19
https://github.com/tgbugs/pyontutils/blob/master/pyontutils/neuron_models/huang2017.py#L337
https://github.com/tgbugs/pyontutils/blob/master/pyontutils/neuron_models/huang2017.py#L338

You can run all your conversion logic inside the class as you do now, its just that all the 'top level' stuff needs to actually be at the top level because of how I implemented it (sort of for a good reason to force that information into places where it is more visible).
2. No.
3. Yes please, name the transgenic lines file allen_transgenic_lines and stick it in the pyontutils/pyontutils folder.

**Comment by tmsincomb** [comment]
L19. Is NeuronEBM and to create 2 different Neurons necessary then?
L337. allen_cell_types has Neuron.write() already at the end after all the Neurons were created. Unless that's not what you meant.

**Comment by tgbugs** [comment]
Ah, I was using L337 as an example of the scope of the call, which is independent of the ordering in the program, but it was clearly a bad example. You can call `Neuron.write()` anywhere in the program and it will do the right thing. The issue is mostly with the fact that class NeuronACT needs to be declared after Config is called and also in global scope.

**Comment by tgbugs** [comment]
This is more or less resolved, any further fixes will be via the neurondm simple rework.
