### ISSUE TITLE
Duplicate class

### ISSUE THREAD

**Issue by memartone** [tgbugs/pyontutils#45]
Why do we have both cortical +SOM neuron and cortical somatostatin neuron?

**Comment by tgbugs** [comment]
One is
```
Neuron
 and (hasExpressionPhenotype some PR_000015665)
 and (hasSomaLocatedIn some neocortex)
```
the other has one additional axiom stating that it is mammalian
```
NeuronCUT
 and (hasExpressionPhenotype some PR_000015665)
 and (hasSomaLocatedIn some neocortex)
 and (hasTaxonRank some NCBITaxon_40674)
```

This is another case of inconsistency in label generation causing issues. I am working on it this weekend so that you don't continue to encounter cases like this.
