### ISSUE TITLE
Erroneus class definition

### ISSUE THREAD

**Issue by memartone** [tgbugs/pyontutils#57]
We have two equivalent classes:  Mammalia neuron, one of which seems to contain the definition for a superior colliculus piriform neuron:
http://uri.neuinfo.org/nif/nifstd/BAMSC1117
NeuronCUT
 and (hasLayerLocationPhenotype some 'Superior colliculus stratum opticum')
 and (hasLocationPhenotype some 'Superior colliculus stratum opticum')
 and (hasTaxonRank some Mammalia)
**

**Comment by memartone** [comment]
We have two equivalent classes for intrinsic neuron, both of which have definitions which are tied to specific brain regions

**Comment by memartone** [comment]
Same with projection neuron.

**Comment by tgbugs** [comment]
These were resolve as issues where there were not enough equivalence class axioms to differentiate two classes so they merged into a single class.
