### ISSUE TITLE
Why are genes classified under sequence feature

### ISSUE THREAD

**Issue by memartone** [tgbugs/pyontutils#59]
http://purl.obolibrary.org/obo/SO_0000110

**Comment by memartone** [comment]
Huang uses Sst that is a sequence feature which is why I suspect that it is not coming back with the query.

**Comment by tgbugs** [comment]
I looked into how genes were modelled in other ontologies with an eye toward unifying their modelling with epigenetic modifications. Sequence feature is what others use and from a discussion with Marga Behrens it seemed that that was also how the epi folks are thinking about what they are measuring.

**Comment by memartone** [comment]
But it is not used consistently.  So it is causing our query to fail.  So pick one or the other.

**Comment by tgbugs** [comment]
Query issue resolved via phenotype indicators.
