### ISSUE TITLE
broken documentation link http://ontology.doc/pyontutils/docstrings.html

### ISSUE THREAD

**Issue by cknoll** [tgbugs/pyontutils#95]
In README.md the url http://ontology.doc/pyontutils/docstrings.html is referenced. However, it seems to be not reachable. Also I have never heard of a `.doc` top level domain and it is also not listed here: <https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains>. Maybe there is a typo in the url?

**Comment by NaincyKumariKnoldus** [comment]
Hey @cknoll Can you give me the appropriate link. I will like to update that!

**Comment by cknoll** [comment]
Unfortunately I am not aware of the correct link. I think @tgbugs probably is.

**Comment by cknoll** [comment]
Update: The documentation seems to be hosted here: http://ontology.neuinfo.org/docs/pyontutils/README.html

However also this file contains the broken link: http://ontology.neuinfo.org/docs/pyontutils/README.html#utility-scripts.

**Comment by NaincyKumariKnoldus** [comment]
Hey @tgbugs Can you please provide me correct link?

**Comment by tgbugs** [comment]
Looks like a bug that snuck through from my development environment. The correct reference is http://ontology.neuinfo.org/docs/docstrings.html.
